version: "3"
services:
  nginx:
    image: "lucasgmm20/udconcord-proxy"
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/my-site.com.crt:/etc/nginx/my-site.com.crt # certificate
      - ./nginx/my-site.com.key:/etc/nginx/my-site.com.key # key
    ports:
      - "3000:443"
    depends_on:
      - server
      - client
    restart: always
  server:
    image: lucasgmm20/udconcord-server
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    expose:
      - "5000"
    restart: always
  client:
    image: lucasgmm20/udconcord-client
    build:
      dockerfile: Dockerfile
      context: "./client"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    expose:
      - "8080"
    depends_on:
      - server
    restart: always
