version: "3"
services:
  apache:
    image: "lucasgmm20/udconcord-proxy"
    build:
      dockerfile: Dockerfile
      context: ./apache
    volumes:
      - ./apache/my-site.com.crt:/usr/my-site.com.crt # certificate
      - ./apache/my-site.com.key:/usr/my-site.com.key # key
    ports:
      - "3000:443"
  server:
    image: lucasgmm20/udconcord-server-dev
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    expose:
      - "5000"
  client:
    image: lucasgmm20/udconcord-client-dev
    build:
      dockerfile: Dockerfile.dev
      context: "./client"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    expose:
      - "8080"
